from __future__ import annotations


def compact_generated_text(text: str) -> str:
    """Compact XCC-generated structural text.

    This helper is intentionally limited to metadata, headings, trees, and
    other text generated by XCC. Collected file contents and Git diff payloads
    must never be passed to it.
    """
    lines = text.splitlines()

    compacted: list[str] = []
    previous_empty = False

    for line in lines:
        cleaned = line.rstrip()
        is_empty = cleaned == ""

        if is_empty and previous_empty:
            continue

        compacted.append(cleaned)
        previous_empty = is_empty

    return "\n".join(compacted).strip() + "\n"

